// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RolesWarden.Db;

#nullable disable

namespace RolesWarden.Migrations
{
    [DbContext(typeof(WardenDbContext))]
    [Migration("20250705011126_AddGuildLogChannelColumns")]
    partial class AddGuildLogChannelColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RolesWarden.Models.GuildConfiguration", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int>("DefaultAction")
                        .HasColumnType("integer")
                        .HasColumnName("default_action");

                    b.Property<int>("IgnoreAdmin")
                        .HasColumnType("integer")
                        .HasColumnName("ignore_admin");

                    b.Property<decimal>("LogChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("log_channel_id");

                    b.Property<int>("LogTypes")
                        .HasColumnType("integer")
                        .HasColumnName("log_types");

                    b.HasKey("GuildId");

                    b.ToTable("guild_config");
                });

            modelBuilder.Entity("RolesWarden.Models.RoleConfiguration", b =>
                {
                    b.Property<decimal>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("RoleId");

                    b.HasIndex("GuildId");

                    b.ToTable("role_config");
                });

            modelBuilder.Entity("RolesWarden.Models.SavedRoles", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<decimal[]>("RoleIds")
                        .HasColumnType("numeric(20,0)[]")
                        .HasColumnName("roles_ids");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("saved_roles");
                });
#pragma warning restore 612, 618
        }
    }
}
